logsBucket: gs://ww_build_logs

steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/www'
      - '-f'
      - './www/Dockerfile'
      - './www'

  # Step 2: Push the Docker image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/www']

  # Step 3: Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'www'
      - '--image'
      - 'gcr.io/$PROJECT_ID/www'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--region'
      - '${_REGION}'
      - '--port'
      - '8080'

substitutions:
  _SERVICE_NAME: 'www'
  _REGION: 'us-central1'

timeout: '1200s' # Adjust timeout if needed